name: sqfentity_sample
description: SqfEntity ORM for Flutter/Dart lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework. 
author: Hüseyin TOKPINAR <hhtokpinar@gmail.com>
homepage: https://github.com/hhtokpinar/sqfEntity


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqfentity: any
  path_provider: any
  intl: ^0.15.7
  cached_network_image: ^1.1.1

  pedantic: ^1.8.0+1
  

dev_dependencies:
#  build_runner: ^1.6.5

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2




# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - sample.db
    - line.png
    - windows-wallpaper.jpg
    - no-picture.png
  
  fonts:
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca-Regular.ttf
          style: normal
    
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Thin.ttf
          style: normal
              
